# Generated by Django 2.2 on 2019-06-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knittingshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='knittingshop_item',
        ),
    ]
